CREATE  TABLE STUDENT_11(SL INT,
SNAME VARCHAR(40),
SMAIL_ID VARCHAR(40),
COURSE VARCHAR(40))
INSERT INTO STUDENT_11 VALUES
(1,'DHANESH','vajaganidhanesh@gmail.com','MERN STACK'),
(2,'DHANI','vajaganidhani@gmail.com','MEAN STACK'),
(3,'CHINTU','vajaganichintu@gmail.com','FULL STACK')

CREATE TABLE COURSE(COURSE_ID INT,
COURSE VARCHAR(40),
COURSE_FEE MONEY)

---------------DROP TABLE COURSE

INSERT INTO COURSE VALUES(101,'MERN STACK',25000),
(102,'MEAN STACK',24000),(103,'Full STACK',27000)

select * from STUDENT_11
select * from COURSE

--INNER JOINS
SELECT  * FROM STUDENT_11 INNER JOIN COURSE ON STUDENT_11.COURSE = COURSE.COURSE